version: '2'
services:
  container:
    build:
      context: ./container
      args:
        - GIT_BRANCH=master
    ports:
      - '1337:1337'
    networks:
      - opentosca
  container-repository:
    build:
      context: ./winery
      args:
        - GIT_BRANCH=master
    ports:
      - '8081:8080'
    networks:
      - opentosca
  web:
    build:
      context: ./web
      args:
        - GIT_BRANCH=master
    ports:
      - '8088:8088'
    networks:
      - opentosca
  engine-plan:
    build: ./engine-plan
    ports:
      - '9443:9443' # https
      - '9763:9763' # http
    networks:
      - opentosca
  engine-ia:
    build: ./engine-ia
    ports:
      - '8080:8080'
    networks:
      - opentosca
  dind:
    image: jpetazzo/dind:latest
    privileged: true
    environment:
      - PORT=2375
      - DOCKER_DAEMON_ARGS=--dns 8.8.8.8 --dns 8.8.4.4 -D
      # Internal DNS settings to run it inside the univeristy network
      # - DOCKER_DAEMON_ARGS=--dns 129.69.211.1 --dns 129.69.215.5 -D
    ports:
      - '9975:2375' # dind
      - '9990-9999:9990-9999' # dind
    # volumes:
    #   - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - opentosca
  winery:
    build:
      context: ./winery
      args:
        - GIT_BRANCH=master
    ports:
      - '8090:8080'
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge
