version: '2'
services:
  container:
    image: opentosca/container:v2.1.0
    ports:
      - '1337:1337'
      - '8081-8087:8081-8087'
    environment:
      PUBLIC_HOSTNAME: ${PUBLIC_HOSTNAME}
      ENGINE_IA_HOSTNAME: engine-ia
      ENGINE_IA_PORT: 8080
      ENGINE_PLAN: ODE
      ENGINE_PLAN_HOSTNAME: engine-plan
      ENGINE_PLAN_ROOT_URL: http://engine-plan:9763/ode
      ENGINE_PLAN_SERVICES_URL: http://engine-plan:9763/ode/processes
      CONTAINER_REPOSITORY_HOSTNAME: container-repository
      CONTAINER_DEPLOYMENT_TESTS: 'false'
      CONTAINER_JAVA_OPTS: ''
    networks:
      - opentosca
  container-repository:
    image: opentosca/winery:v2.1.0-M1
    networks:
      - opentosca
  ui:
    image: opentosca/ui:v2.1.0
    ports:
      - '8088:8080'
    networks:
      - opentosca
  engine-plan:
    image: opentosca/ode:v2.1.0
    ports:
      - '9763:9763' # http
    networks:
      - opentosca
  engine-ia:
    image: opentosca/engine-ia:v2.1.0
    ports:
      - '8090:8080'
      # - '1883:1883' # MQTT
    networks:
      - opentosca
  winery:
    image: opentosca/winery:v2.1.0-M1
    ports:
      - '8080:8080'
    networks:
      - opentosca
  dind:
    image: jpetazzo/dind:latest
    privileged: true
    environment:
      - PORT=2375
      - DOCKER_DAEMON_ARGS=--dns 8.8.8.8 --dns 8.8.4.4 -D
    ports:
      # - '9975:2375'
      - '9990-9999:9990-9999'
    # volumes:
    #   - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge
