#
# docker-compose build --force-rm [--no-cache [<SERVICE_NAME>...]]
# docker-compose up -d --remove-orphans
# docker-compose logs -f [<SERVICE_NAME>...]
# docker-compose down -v --remove-orphans
#
version: '2'
services:
  tomcat:
    build: ./tomcat
    ports:
      - '1337:1337' # container (http)
      - '8080:8080' # tomcat (http)
      - '9443:9443' # bps (https)
      - '9763:9763' # bps (http)
      # - '9975:2375' # dind (tcp)
    volumes:
      - '/usr/local/tomcat/webapps'
    environment:
      - TOMCAT_USERNAME=tcManager
      - TOMCAT_PASSWORD=4Syq5MQeedIDzzP6BG7b
  opentosca-container:
    build:
      context: ./opentosca-container
      args:
        - OPENTOSCA_CONTAINER_BRANCH=master
    network_mode: 'service:tomcat'
  bps:
    build: ./bps
    network_mode: 'service:tomcat'
  dind:
    image: jpetazzo/dind:latest
    privileged: true
    network_mode: 'service:tomcat'
    environment:
      - PORT=2375
      - DOCKER_DAEMON_ARGS=--dns 8.8.8.8 --dns 8.8.4.4 -D
  opentosca-ui:
    build:
      context: ./opentosca-ui
      args:
        - OPENTOSCA_UI_BRANCH=master
    volumes_from:
      - tomcat
    depends_on:
      - tomcat
  winery:
    build:
      context: ./winery
      args:
        - WINERY_BRANCH=master
    volumes_from:
      - tomcat
    depends_on:
      - tomcat
