version: '2'
services:
  tomcat:
    build: ./tomcat
    ports:
    - '8080:8080'
    - '8778:8778'
    volumes:
    - '/opt/tomcat/webapps'
    environment:
      REMOTE_HOSTNAME: '${DOCKER_HOSTNAME}' # default: localhost
    network_mode: 'host' # required because OpenTOSCA has localhost endpoints hard-coded
  bps:
    build: ./bps
    ports:
    - '9443:9443'
    - '9763:9763'
    environment:
      REMOTE_HOSTNAME: '${DOCKER_HOSTNAME}' # default: localhost
    network_mode: 'host' # required because OpenTOSCA has localhost endpoints hard-coded
  engine:
    build: ./engine
    ports:
    - '1337:1337'
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
    - tomcat
    - bps
    network_mode: 'host' # required because OpenTOSCA has localhost endpoints hard-coded
  admin-ui:
    build: ./admin-ui
    volumes_from:
    - tomcat
    depends_on:
    - tomcat
    - engine
  root-ui:
    build: ./root-ui
    volumes_from:
    - tomcat
    depends_on:
    - tomcat
  vinothek:
    build: ./vinothek
    volumes_from:
    - tomcat
    depends_on:
    - tomcat
    - engine
  winery:
    build: ./winery
    volumes_from:
    - tomcat
    depends_on:
    - tomcat

#
# export DOCKER_HOSTNAME=docker
#
# docker-compose build --force-rm
# docker-compose up -d --remove-orphans
# docker-compose logs -f
# docker-compose port SERVICE_NAME PRIVATE_PORT
# docker-compose down -v --remove-orphans
#
