version: '2'
services:
  container:
    image: opentosca/container
    ports:
      - '1337:1337'
      - '8081-8087:8081-8087'
    environment:
      - PUBLIC_HOSTNAME=container
      - PUBLIC_IP 192.168.1.2 # enter IP where the engine-ia can be accessed from outside
      - ENGINE_IA_HOSTNAME=engine-ia
      - ENGINE_PLAN_HOSTNAME=engine-plan
      - CONTAINER_REPOSITORY_HOSTNAME=container-repository
      - CONTAINER_DEPLOYMENT_TESTS=false
    # volumes:
    #   - <path on host system>:/tmp/opentosca
    networks:
      - opentosca
  container-repository:
    image: opentosca/winery
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
    networks:
      - opentosca
  ui:
    image: opentosca/ui
    ports:
      - '8088:8080'
    networks:
      - opentosca
  engine-plan:
    image: opentosca/bps
    ports:
      - '9443:9443' # https
      - '9763:9763' # http
    environment:
      - PUBLIC_HOSTNAME=engine-plan
    networks:
      - opentosca
  engine-ia:
    image: opentosca/engine-ia
    ports:
      - '8090:8080'
      - '1883:1883 # MQTT
    # volumes:
    #   - <path on host system>:/usr/local/tomcat/webapps
    networks:
      - opentosca
  winery:
    image: opentosca/winery
    ports:
      - '8080:8080'
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
    networks:
      - opentosca
  dind:
    image: jpetazzo/dind:latest
    privileged: true
    environment:
      - PORT=2375
      - DOCKER_DAEMON_ARGS=--dns 8.8.8.8 --dns 8.8.4.4 -D
      # Internal DNS settings to run it inside the university network
      # - DOCKER_DAEMON_ARGS=--dns 129.69.211.1 --dns 129.69.215.5 -D
    ports:
      # - '9975:2375' # dind
      - '9990-9999:9990-9999' # dind
    # volumes:
    #   - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge
