version: '2'
services:
  engine:
    image: opentosca/engine
    ports:
    - '1337:1337' # engine
    - '8080:8080' # tomcat
    - '8778:8778' # tomcat
    - '9443:9443' # bps
    - '9763:9763' # bps
    volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/tmp:/tmp' # shared temp directory among containers
    - '/endpoints'
    environment:
      OPENTOSCA_ENDPOINTS_JSON: '/endpoints/opentosca.json'
  tomcat:
    image: opentosca/tomcat
    volumes:
    - '/opt/tomcat/webapps'
    environment:
      REMOTE_HOSTNAME: '${DOCKER_HOSTNAME}' # default: localhost
    network_mode: 'service:engine'
  bps:
    image: opentosca/bps
    environment:
      REMOTE_HOSTNAME: '${DOCKER_HOSTNAME}' # default: localhost
    network_mode: 'service:engine'

  admin-ui:
    image: opentosca/admin-ui
    volumes_from:
    - tomcat
    depends_on:
    - engine
    - tomcat
    - bps
  root-ui:
    image: opentosca/root-ui
    volumes_from:
    - tomcat
    depends_on:
    - tomcat
  vinothek:
    image: opentosca/vinothek
    volumes_from:
    - tomcat
    depends_on:
    - engine
    - tomcat
    - bps
  winery:
    image: opentosca/winery
    volumes_from:
    - tomcat
    depends_on:
    - tomcat

  pre-runner:
    build: ./runner/pre
    volumes_from:
    - engine
    volumes:
    - '${RUNNER_CSARS_DIR}:/csars'
    depends_on:
    - admin-ui
    network_mode: 'service:engine'
  runner:
    build: ${RUNNER_BUILD_DIR}
    volumes_from:
    - engine
    volumes:
    - '${RUNNER_CONTEXT_DIR}:/context'
    - '${RUNNER_CSARS_DIR}:/csars'
    depends_on:
    - admin-ui
    - vinothek
    network_mode: 'service:engine'
  post-runner:
    build: ./runner/post
    volumes_from:
    - engine
    depends_on:
    - admin-ui
    network_mode: 'service:engine'

#
# export DOCKER_HOSTNAME=docker
#
# docker-compose -f docker-compose-runner.yml pull
# docker-compose -f docker-compose-runner.yml build --force-rm
# docker-compose -f docker-compose-runner.yml up --remove-orphans pre-runner
# docker-compose -f docker-compose-runner.yml up --remove-orphans runner
# docker-compose -f docker-compose-runner.yml up --remove-orphans post-runner
# docker-compose -f docker-compose-runner.yml logs -f
# docker-compose -f docker-compose-runner.yml down -v --remove-orphans
#
