version: '2'
services:
  container:
    image: opentosca/container-dev
    ports:
      - '1337:1337'
      - '8001:8001' # Expose JAVA remote debugging port
    environment:
      - CONTAINER_HOSTNAME=container
      - CONTAINER_REPOSITORY_HOSTNAME=container-repository
      - ENGINE_IA_HOSTNAME=engine-ia
      - ENGINE_PLAN_HOSTNAME=engine-plan
      - ENGINE_PLAN=ODE # Change to "BPS" to use WSO2 BPS as plan engine
      - ENGINE_PLAN_ROOT_URL=http://engine-plan:9763/ode # Change value to "https://engine-plan:9443" when using BPS as plan engine
      - ENGINE_PLAN_SERVICES_URL=http://engine-plan:9763/ode/processes # Change value to "http://engine-plan:9763/services" when using BPS as plan engine
      #- ENGINE_PLAN_USER_NAME=admin # Uncomment when using BPS as plan engine
      #- ENGINE_PLAN_PWD=admin # Uncomment when using BPS as plan engine
    networks:
      - opentosca
  container-repository:
    image: opentosca/winery
    ports:
      - '8081:8080'
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
    networks:
      - opentosca
  ui:
    image: opentosca/ui
    ports:
      - '8088:8080'
    networks:
      - opentosca
  engine-plan:
    image: opentosca/engine-plan-ode # Change to "opentosca/engine-plan" to use WSO2 BPS as plan engine
    ports:
      #- '9443:9443' # Uncomment when using BPS as plan engine
      - '9763:9763' # http
      - '5555:8000' # Remote debugging port
    environment:
      - ENGINE_PLAN_HOSTNAME=engine-plan
      - ENGINE_PLAN_PORT=9763
      - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n # Enable remote debugging of Apache ODE
    networks:
      - opentosca
  engine-ia:
    image: opentosca/engine-ia
    ports:
      - '8080:8080'
    networks:
      - opentosca
  dind:
    image: jpetazzo/dind:latest
    privileged: true
    environment:
      - PORT=2375
      - DOCKER_DAEMON_ARGS=--dns 8.8.8.8 --dns 8.8.4.4 -D
      # Internal DNS settings to run it inside the univeristy network
      #- DOCKER_DAEMON_ARGS=--dns 129.69.211.1 --dns 129.69.215.5 -D
    ports:
      # - '9975:2375' # dind
      - '9990-9999:9990-9999' # dind
    # volumes:
    #   - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - opentosca
  winery:
    image: opentosca/winery
    ports:
      - '8090:8080'
    # volumes:
    #   - <path on host system>:/var/opentosca/repository
    networks:
      - opentosca
networks:
  opentosca:
    driver: bridge
